services:
  discovery-server:
    image: discovery-server:latest
    container_name: discovery-server
    ports:
      - "8761:8761"
    networks:
      - microservice-net

networks:
  microservice-net:
    external: true
